spring.cloud.vault.enabled=true
spring.cloud.vault.uri=${VAULT_URI}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN}

spring.config.import=optional:vault://
spring.cloud.vault.kv.enabled=true

spring.cloud.vault.kv.backend=${VAULT_MOUNT}

spring.cloud.vault.kv.default-context=${VAULT_APP}
spring.profiles.active=${ENV}
spring.cloud.vault.kv.profile-separator=/

spring.cloud.vault.fail-fast=true
