spring.application.name=eco-auth
server.port=8081

spring.cloud.vault.enabled=true
spring.cloud.vault.uri=${VAULT_URI}

spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN}

spring.cloud.vault.kv.enabled=true
spring.config.import=vault:///${SECRETS_PATH}


spring.cloud.vault.fail-fast=true
